[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "hello"
path = "src/hello-world/main.rs"

[[bin]]
name = "hello_nostd"
path = "src/hello-world-nostd/main.rs"
