Import( 'env' )

cpp_env = env.Clone()

cpp_env.AppendUnique(CCFLAGS = ['-std=c++11'])
cpp_env.Program('cpp_vtable', ['v_table.cpp'])

env.Install('#bin', 'cpp_vtable')
env.Alias('install', '#bin')

